[config]
reload_apps = false
reload_apps_list = []
# set_wallpaper = false

[config.reload]

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.cache/safalQuick/colors.json"

